const createError = require('http-errors');
module.exports.validateUser = async (req, res, next) => {
  try {
  } catch (error) {}
};
